version: '3.8'

services:
  inception_base:
    container_name: inception
    image: inception:base
    build:
      context: ./requirements/inception_base
      dockerfile: Dockerfile
    restart: "no"

  nginx:
    container_name: nginx
    image: nginx:inception
    depends_on:
      - inception_base
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    restart: "unless-stopped"
    stop_signal: SIGTERM
    ports:
      - 443:443
    networks:
      - netception
    volumes:
      - WP_Website:/var/www/html
  
  wordpress:
    container_name: wordpress
    image: wordpress:inception
    depends_on:
      - inception_base
      - mariadb
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    restart: "unless-stopped"
    stop_signal: SIGTERM
    env_file:
      - .env
    ports:
      - 9000:9000
    networks:
      - netception
    volumes:
      - WP_Website:/var/www/html

  mariadb:
    container_name: mariadb
    image: mariadb:inception
    depends_on:
      - inception_base
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    restart: "unless-stopped"
    stop_signal: SIGTERM
    env_file:
      - .env
    ports:
      - 3306-3306
    networks:
      - netception
    volumes:
      - WP_Database:/var/lib/mysql

networks:
  netception:
    name: netception
    driver: bridge

volumes:
  WP_Website:
    name: WP_Website
    driver: local
  WP_Database:
    name: WP_Database
    driver: local
